on:
  push:
  release:
        types: [published, created, edited]
jobs:
  releasing:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - uses: heinrichreimer/action-github-changelog-generator@v2.1.1

